services:

  app:
    build:
      dockerfile: ./docker/app/dev.Dockerfile
    volumes: # Mount source code as volume for development
      - ./:/fumnail/app
  
  worker:
    build:
      dockerfile: ./docker/worker/dev.Dockerfile
    volumes: # Mount source code as volume for development
      - ./:/fumnail/worker
      